// Code generated by protoc-gen-go.
// source: network.proto
// DO NOT EDIT!

package onemon

import proto "github.com/golang/protobuf/proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal

// ID: 12
type NetworkFlow struct {
	Pid     uint64 `protobuf:"varint,1,opt,name=pid" json:"pid,omitempty"`
	Proto   uint32 `protobuf:"varint,2,opt,name=proto" json:"proto,omitempty"`
	Srcip   uint32 `protobuf:"fixed32,3,opt,name=srcip" json:"srcip,omitempty"`
	Dstip   uint32 `protobuf:"fixed32,4,opt,name=dstip" json:"dstip,omitempty"`
	Srcport uint32 `protobuf:"varint,5,opt,name=srcport" json:"srcport,omitempty"`
	Dstport uint32 `protobuf:"varint,6,opt,name=dstport" json:"dstport,omitempty"`
}

func (m *NetworkFlow) Reset()         { *m = NetworkFlow{} }
func (m *NetworkFlow) String() string { return proto.CompactTextString(m) }
func (*NetworkFlow) ProtoMessage()    {}

func init() {
}
