// Code generated by protoc-gen-go.
// source: process.proto
// DO NOT EDIT!

package onemon

import proto "github.com/golang/protobuf/proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal

type ProcessStatus int32

const (
	ProcessStatus_Create    ProcessStatus = 0
	ProcessStatus_Terminate ProcessStatus = 1
)

var ProcessStatus_name = map[int32]string{
	0: "Create",
	1: "Terminate",
}
var ProcessStatus_value = map[string]int32{
	"Create":    0,
	"Terminate": 1,
}

func (x ProcessStatus) String() string {
	return proto.EnumName(ProcessStatus_name, int32(x))
}

type Process struct {
	Status  ProcessStatus `protobuf:"varint,1,opt,name=status,enum=onemon.ProcessStatus" json:"status,omitempty"`
	Pid     uint64        `protobuf:"varint,2,opt,name=pid" json:"pid,omitempty"`
	Ppid    uint64        `protobuf:"varint,3,opt,name=ppid" json:"ppid,omitempty"`
	Image   string        `protobuf:"bytes,4,opt,name=image" json:"image,omitempty"`
	Command string        `protobuf:"bytes,5,opt,name=command" json:"command,omitempty"`
}

func (m *Process) Reset()         { *m = Process{} }
func (m *Process) String() string { return proto.CompactTextString(m) }
func (*Process) ProtoMessage()    {}

func init() {
	proto.RegisterEnum("onemon.ProcessStatus", ProcessStatus_name, ProcessStatus_value)
}
