// Code generated by protoc-gen-go. DO NOT EDIT.
// source: syscalls.proto

package onemon

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type SyscallKind int32

const (
	SyscallKind_Unk SyscallKind = 0
)

var SyscallKind_name = map[int32]string{
	0: "Unk",
}
var SyscallKind_value = map[string]int32{
	"Unk": 0,
}

func (x SyscallKind) String() string {
	return proto.EnumName(SyscallKind_name, int32(x))
}
func (SyscallKind) EnumDescriptor() ([]byte, []int) { return fileDescriptor12, []int{0} }

type SyscallIKind int32

const (
	SyscallIKind_UnkI SyscallIKind = 0
)

var SyscallIKind_name = map[int32]string{
	0: "UnkI",
}
var SyscallIKind_value = map[string]int32{
	"UnkI": 0,
}

func (x SyscallIKind) String() string {
	return proto.EnumName(SyscallIKind_name, int32(x))
}
func (SyscallIKind) EnumDescriptor() ([]byte, []int) { return fileDescriptor12, []int{1} }

type SyscallSKind int32

const (
	SyscallSKind_UnkS                            SyscallSKind = 0
	SyscallSKind_JsGlobalObjectDefaultEvalHelper SyscallSKind = 1
)

var SyscallSKind_name = map[int32]string{
	0: "UnkS",
	1: "JsGlobalObjectDefaultEvalHelper",
}
var SyscallSKind_value = map[string]int32{
	"UnkS": 0,
	"JsGlobalObjectDefaultEvalHelper": 1,
}

func (x SyscallSKind) String() string {
	return proto.EnumName(SyscallSKind_name, int32(x))
}
func (SyscallSKind) EnumDescriptor() ([]byte, []int) { return fileDescriptor12, []int{2} }

type SyscallSSKind int32

const (
	SyscallSSKind_COleScript_Compile SyscallSSKind = 0
)

var SyscallSSKind_name = map[int32]string{
	0: "COleScript_Compile",
}
var SyscallSSKind_value = map[string]int32{
	"COleScript_Compile": 0,
}

func (x SyscallSSKind) String() string {
	return proto.EnumName(SyscallSSKind_name, int32(x))
}
func (SyscallSSKind) EnumDescriptor() ([]byte, []int) { return fileDescriptor12, []int{3} }

// ID: 100
type Syscall struct {
	Ts   uint32      `protobuf:"varint,3,opt,name=ts" json:"ts,omitempty"`
	Pid  uint64      `protobuf:"varint,1,opt,name=pid" json:"pid,omitempty"`
	Kind SyscallKind `protobuf:"varint,2,opt,name=kind,enum=onemon.SyscallKind" json:"kind,omitempty"`
}

func (m *Syscall) Reset()                    { *m = Syscall{} }
func (m *Syscall) String() string            { return proto.CompactTextString(m) }
func (*Syscall) ProtoMessage()               {}
func (*Syscall) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{0} }

func (m *Syscall) GetTs() uint32 {
	if m != nil {
		return m.Ts
	}
	return 0
}

func (m *Syscall) GetPid() uint64 {
	if m != nil {
		return m.Pid
	}
	return 0
}

func (m *Syscall) GetKind() SyscallKind {
	if m != nil {
		return m.Kind
	}
	return SyscallKind_Unk
}

// ID: 101
type SyscallI struct {
	Ts   uint32       `protobuf:"varint,4,opt,name=ts" json:"ts,omitempty"`
	Pid  uint64       `protobuf:"varint,1,opt,name=pid" json:"pid,omitempty"`
	Kind SyscallIKind `protobuf:"varint,2,opt,name=kind,enum=onemon.SyscallIKind" json:"kind,omitempty"`
	Arg0 uint64       `protobuf:"varint,3,opt,name=arg0" json:"arg0,omitempty"`
}

func (m *SyscallI) Reset()                    { *m = SyscallI{} }
func (m *SyscallI) String() string            { return proto.CompactTextString(m) }
func (*SyscallI) ProtoMessage()               {}
func (*SyscallI) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{1} }

func (m *SyscallI) GetTs() uint32 {
	if m != nil {
		return m.Ts
	}
	return 0
}

func (m *SyscallI) GetPid() uint64 {
	if m != nil {
		return m.Pid
	}
	return 0
}

func (m *SyscallI) GetKind() SyscallIKind {
	if m != nil {
		return m.Kind
	}
	return SyscallIKind_UnkI
}

func (m *SyscallI) GetArg0() uint64 {
	if m != nil {
		return m.Arg0
	}
	return 0
}

// ID: 102
type SyscallS struct {
	Ts   uint32       `protobuf:"varint,4,opt,name=ts" json:"ts,omitempty"`
	Pid  uint64       `protobuf:"varint,1,opt,name=pid" json:"pid,omitempty"`
	Kind SyscallSKind `protobuf:"varint,2,opt,name=kind,enum=onemon.SyscallSKind" json:"kind,omitempty"`
	Arg0 string       `protobuf:"bytes,3,opt,name=arg0" json:"arg0,omitempty"`
}

func (m *SyscallS) Reset()                    { *m = SyscallS{} }
func (m *SyscallS) String() string            { return proto.CompactTextString(m) }
func (*SyscallS) ProtoMessage()               {}
func (*SyscallS) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{2} }

func (m *SyscallS) GetTs() uint32 {
	if m != nil {
		return m.Ts
	}
	return 0
}

func (m *SyscallS) GetPid() uint64 {
	if m != nil {
		return m.Pid
	}
	return 0
}

func (m *SyscallS) GetKind() SyscallSKind {
	if m != nil {
		return m.Kind
	}
	return SyscallSKind_UnkS
}

func (m *SyscallS) GetArg0() string {
	if m != nil {
		return m.Arg0
	}
	return ""
}

// ID: 103
type SyscallSS struct {
	Ts   uint32        `protobuf:"varint,5,opt,name=ts" json:"ts,omitempty"`
	Pid  uint64        `protobuf:"varint,1,opt,name=pid" json:"pid,omitempty"`
	Kind SyscallSSKind `protobuf:"varint,2,opt,name=kind,enum=onemon.SyscallSSKind" json:"kind,omitempty"`
	Arg0 string        `protobuf:"bytes,3,opt,name=arg0" json:"arg0,omitempty"`
	Arg1 string        `protobuf:"bytes,4,opt,name=arg1" json:"arg1,omitempty"`
}

func (m *SyscallSS) Reset()                    { *m = SyscallSS{} }
func (m *SyscallSS) String() string            { return proto.CompactTextString(m) }
func (*SyscallSS) ProtoMessage()               {}
func (*SyscallSS) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{3} }

func (m *SyscallSS) GetTs() uint32 {
	if m != nil {
		return m.Ts
	}
	return 0
}

func (m *SyscallSS) GetPid() uint64 {
	if m != nil {
		return m.Pid
	}
	return 0
}

func (m *SyscallSS) GetKind() SyscallSSKind {
	if m != nil {
		return m.Kind
	}
	return SyscallSSKind_COleScript_Compile
}

func (m *SyscallSS) GetArg0() string {
	if m != nil {
		return m.Arg0
	}
	return ""
}

func (m *SyscallSS) GetArg1() string {
	if m != nil {
		return m.Arg1
	}
	return ""
}

func init() {
	proto.RegisterType((*Syscall)(nil), "onemon.Syscall")
	proto.RegisterType((*SyscallI)(nil), "onemon.SyscallI")
	proto.RegisterType((*SyscallS)(nil), "onemon.SyscallS")
	proto.RegisterType((*SyscallSS)(nil), "onemon.SyscallSS")
	proto.RegisterEnum("onemon.SyscallKind", SyscallKind_name, SyscallKind_value)
	proto.RegisterEnum("onemon.SyscallIKind", SyscallIKind_name, SyscallIKind_value)
	proto.RegisterEnum("onemon.SyscallSKind", SyscallSKind_name, SyscallSKind_value)
	proto.RegisterEnum("onemon.SyscallSSKind", SyscallSSKind_name, SyscallSSKind_value)
}

func init() { proto.RegisterFile("syscalls.proto", fileDescriptor12) }

var fileDescriptor12 = []byte{
}
